[project]
name = "heimdall"
version = "0.1.0"
requires-python = ">=3.14"
dependencies = [
    "earthcarekit>=0.19.0",
    "goes2go>=2025.10.0",
    "metpy>=1.7.1",
    "netcdf4>=1.7.4",
    "pandas>=3.0.6",
    "pyresample>=1.35.0",
    "satpy>=0.60.0",
    "tqdm>=4.70.1",
    "xarray>=2026.9.0",
    "cfgrib>=0.9.15.1",
    "eccodes>=2.49.0",
    "eccodeslib>=2.49.0.30 ; sys_platform != 'win32'",
    "torch>=2.14.1",
    "xbatcher>=0.4.0",
    "torchmetrics>=1.9.0",
]
